services:
  broker:
    image: apache/kafka:4.3.1
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data        # ← ahora coincide con el volumen
      CLUSTER_ID: "gTBb85_WRXu6oQgq-brTQw"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

  kafka-init:
    image: apache/kafka:4.3.1                   # misma versión que el broker
    container_name: kafka-init
    depends_on:
      broker:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "for t in watering.requests watering.commands watering.telemetry watering.events watering.notifications; do
         /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:29092
           --create --if-not-exists --topic $$t --partitions 1 --replication-factor 1;
       done;
       echo 'topics listos';
       /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:29092 --list"
    restart: "no"

volumes:
  kafka-data: